const ResortTypes = {
  UPLOAD_RESORT_OBJECTS: 'UPLOAD_RESORT_OBJECTS',
  GET_RESORT_OBJECT: 'GET_RESORT_OBJECT',
  UPDATE_ATTRIBUTE_MAP: 'UPDATE_ATTRIBUTE_MAP',
  UPDATE_RESORT_ERROR_OBJECT: 'UPDATE_RESORT_ERROR_OBJECT',
};

export default ResortTypes;
